name: Pre-release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    name: Create Pre-release
    runs-on: ubuntu-latest
    permissions:
      contents: write # for github releases
      id-token: write # for keyless signing

    steps:

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4
        with:
          fetch-depth: 0 # fetch all commits and tags
      - name: Prepare tag committer config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Determine tag
        id: determine-tag
        run: |
          describe="$(git describe --match 'v[0-9]*' --exclude 'v*-*' --tags 2>/dev/null || true)"
          if [[ -z "$describe" ]]; then
            describe=v0.0.0-0-g0
          fi
          ver="${describe%%-*}"
          snap="${describe#*-}"
          new_tag="$ver-snap.$snap"
          echo "ver=$ver" >>"$GITHUB_OUTPUT"
          echo "snap=$snap" >>"$GITHUB_OUTPUT"
          echo "new_tag=$new_tag" >>"$GITHUB_OUTPUT"
          git tag -a "$new_tag" -m "$new_tag"
          git push origin "$new_tag"

      - name: Setup Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed #v5
        with:
          go-version: '1.22' # Update to the desired Go version, or "stable"

      - name: Prepare prerelease config
        # goreleaser only supports includes for paid version
        run: |
          cp -v .goreleaser.yaml /tmp/
          echo >>/tmp/.goreleaser.yaml
          echo >>/tmp/.goreleaser.yaml 'release:'
          echo >>/tmp/.goreleaser.yaml '  prerelease: true'
          echo
          cat /tmp/.goreleaser.yaml

      - name: Install cosign for signatures
        uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a #v3.8.1

      - name: Install syft for sboms
        uses: anchore/sbom-action/download-syft@f325610c9f50a54015d37c8d16cb3b0e2c8f4de0 #v0.18.0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf #v6
        with:
          version: '~> v2.4.8'
          args: --verbose release --skip=announce,validate --clean --config /tmp/.goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.determine-tag.outputs.new_tag }}
          release_name: ${{ steps.determine-tag.outputs.new_tag }}
